------------------------
/Users/laurenz/graphql-mongodb/uml_diagramms/Resource_GeographicAddress.png

@startuml DigitalIdentity
hide circle
hide methods
hide stereotype
show <<Enumeration>> stereotype
skinparam class {
   BackgroundColor<<Enumeration>> #E6F5F7
   BackgroundColor<<Ref>> #FFFFE0
   BackgroundColor<<Pivot>> #FFFFFFF
   BackgroundColor #FCF2E3
}

class DigitalIdentity <<Pivot>> {
    id : String
    href : String
    nickname : String
    creationDate : Date
    status : String
}

class ResourceRef <<Ref>> {
    id: String
    href: String
    name: String
}

DigitalIdentity *-->  "0..1" ResourceRef : resourceIdentified

@enduml

PlantUML version 1.2019.00(Sun Jan 13 16:46:42 CET 2019)
(GPL source distribution)
Java Runtime: OpenJDK Runtime Environment
JVM: OpenJDK 64-Bit Server VM
Java Version: 13+13-Ubuntu-0ubunt1
Operating System: Linux
OS Version: 5.0.0-37-generic
Default Encoding: UTF-8
Language: en
Country: US

------------------------
